name: My first GitHub Action

on: [push]

jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hell world !!!!!"
            - run: echo "this is step number  02"
